####################################################################################
# Repository > Settings > Secrets:
# Bintray
#   BINTRAY_API_KEY   : API KEY for Bintray uploading.
#   BINTRAY_GPG_PASS  : Signing key for Bintray uploading.
####################################################################################
name: assemble Kotlin library jar
on:
  - push
jobs:
  assemble-kotlin-artifacts:
    runs-on: ubuntu-20.04
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    env:
      _JAVA_OPTIONS: "-Xmx4g -Dfile.encoding=UTF-8"
      TZ: Asia/Tokyo
      BINTRAY_API_KEY: ${{secrets.BINTRAY_API_KEY}}
      BINTRAY_GPG_PASS: ${{secrets.BINTRAY_GPG_PASS}}
    steps:
      - uses: actions/checkout@v2.0.0
      - name: "cache / gradle"
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: "environments / java"
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: "environments"
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "PWD=$PWD"
          echo "PATH=$path"
          echo "java `java -version`: `which java`"
          gradle -v
          ls -al
      - name: "kotlin / test / format"
        run: |
          ./gradlew format
          if [ "`git diff | grep '.kt'`" != "" ]; then
            echo "kotlin format error"
            echo "run -> ./gradlew format"
            exit 1
          fi
      - name: "kotlin / build"
        run: |
          ./gradlew build
      - name: "kotlin / publish / test-results"
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: "kotlin / publish / bintray"
        run: |
          ./gradlew bintrayUpload
